repository:
  # Repository name
  name: metodologia_para_data_science_20252
  # Repository description
  description: Guías y documentación para Metodología para Data Science 2025-2
  # Enable issues, projects, wiki
  has_issues: true
  has_projects: true
  has_wiki: false
  # Default branch (main)
  default_branch: main

# Branch protection rules
branches:
  - name: main
    protection:
      # Require pull request reviews before merging
      required_pull_request_reviews:
        required_approving_review_count: 1
        dismiss_stale_reviews: true
        require_code_owner_reviews: false
        dismissal_restrictions:
          users: ["aladelca"]

      # Only allow specific users to bypass
      restrictions:
        users: ["aladelca"]
        teams: []

      # Require status checks to pass before merging
      required_status_checks:
        strict: true
        contexts: ["check-branch-protection", "enforce-review-requirements", "documentation-check"]

      # Include administrators in restrictions
      enforce_admins: true

      # Prevent direct pushes to main
      allow_force_pushes: false
      allow_deletions: false
